---
- name: Send slack message
  hosts: localhost
  tasks:
    - name: Notify Slack that EC2 instance has been created
      community.general.slack:
        token: "{{ token }}"
        msg: |
            ```
            {{ message }}
            ```
        channel: '#ansiblefest-demo'
        color: good
        username: 'AnsibleFest-bot'
        link_names: 0
        parse: 'none'
